name: On commit on main branch

on:
  push:
    branches:
      - main

jobs:
  check-typescript-code:
    name: Check typescript code
    uses: ./.github/workflows/callable__check_typescript_code.yaml
    secrets: inherit

  build-and-release:
    name: Build and release
    uses: ./.github/workflows/callable__build_and_release.yaml
    needs: check-typescript-code
    secrets: inherit
